baseURL = 'https://rrulyx.github.io/HugoBlog/'

publishDir = "docs"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

languageCode = 'en-us'
title = 'My journey in IGD301'
theme = 'hermit-v24'

pygmentsCodefences  = true
pygmentsUseClasses  = true

rssLimit = 10

# copyright = ""
enableEmoji = true

[params.author]
  name = "Julien Jampsin"
#  about = "LINK"

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  description = "Follow me in the discovery of Extended Reality"
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "Follow me in the discovery of Extended Reality"
  # footerCopyright = "CHANGE ME FOOTER COPYRIGHT"
  # bgImg = ""
  # gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = false
  # readTimeSeparator = "CHANGE ME READ TIME"
  # legacyLayout = false
  shareSocial = true

#  [[params.socialLinks]]
#    name = "mastodon"
#    url = "https://joinmastodon.org/"

 # [[params.socialLinks]]
 #   name = "x"
 #   url = "https://twitter.com/"

 # [[params.socialLinks]]
 #   name = "github"
 #   url = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "Setup"
    url = "tags/setup/"
    weight = 10


#  [[menu.main]]
#    name = "About"
#    url = "about-hugo/"
#    weight = 20