baseURL = 'https://JulienJ.fr/'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hermit-v2'

pygmentsCodefences  = true
pygmentsUseClasses  = true

rssLimit = 10

copyright = "CHANGE ME"
enableEmoji = true

[params.author]
  name = "Julien Jampsin"
#  about = "LINK"

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # description = "CHANGE ME SITE DESCRIPTION"
  # images = [""]
  themeColor = "#494f5c"

  #homeSubtitle = "CHANGE ME HOME SUBTITLE"
  footerCopyright = "CHANGE ME FOOTER COPYRIGHT"
  # bgImg = ""
  # gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = true
  readTimeSeparator = "CHANGE ME READ TIME"
  # legacyLayout = false
  shareSocial = true

#  [[params.socialLinks]]
#    name = "mastodon"
#    url = "https://joinmastodon.org/"

 # [[params.socialLinks]]
 #   name = "x"
 #   url = "https://twitter.com/"

 # [[params.socialLinks]]
 #   name = "github"
 #   url = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about-hugo/"
    weight = 20